spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rafia
      username:
      password:

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration