server:
  shutdown: graceful
spring:
  web:
    graceful
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rafia
      username:
      password:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest
jwt:
  secret-key: ${secret-key}
  expiration: ${expiration} # 7days

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
